### ISSUE TITLE
Adding AfferentPopulation types together yield odd plots

### ISSUE THREAD

**Issue by TorSalve** [hsaal/touchsim#3]
Thanks for the great library. I am trying to add two variables of type ``AfferentPopulation`` together, but unfortunately, the resulting plot yields an odd result.

```python
pc = ts.affpop_hand(affclass='PC')
ra = ts.affpop_hand(affclass='RA')
a = pc + ra

plot() * plot(pc) + plot() * plot(ra) + plot() * plot(a)
```
yields
![index](https://user-images.githubusercontent.com/11175661/123826266-e7abfb00-d8ff-11eb-8641-4089c79680b3.png)

I can change the last line to
```python
plot() * plot(pc) + plot() * plot(ra) + plot() * plot(pc) * plot(ra)
```
and get a good result, but I can not do ``a.response(s)`` (where ``s`` is some stimulus) and get a meaningful result (see below).
![index](https://user-images.githubusercontent.com/11175661/123826640-3f4a6680-d900-11eb-8548-5e09b9dc595d.png)

How can I fix this?

**Comment by hsaal** [comment]
Thanks for letting me know! I have pushed a fix that should address this issue.

Each `Afferent` and `AfferentPopulation` object has a `surface` property, which creates the coordinate system. This can be set to the standard one for the hand or any user-defined ones. In this case, the surface didn't properly get copied over when merging the two populations. If you spot any similar issues, please let me know and feel free to re-open the issue!
